name: Run Flask Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-flask-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1' # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask_sqlalchemy

    - name: Set up database
      run: |
        python -c "from app import db; db.create_all()"
      env:
        FLASK_APP: app.py

    - name: Run Flask application
      run: python app.py
